name: simple_json_persistence
description: Flutter data storage based on simple json files with support for multiple
  storage instances, streams, etc.
version: 2.0.0-nullsafety.3
homepage: https://github.com/hpoul/simple_json_persistence

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path: ^1.8.0
  logging: ^1.0.0
  rxdart: '>=0.26.0 <1.0.0'
  path_provider: ^2.0.0
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#  test: ">=1.5.0 <2.0.0"
  pedantic: ^1.10.0
  fake_async: ^1.2.0
  logging_appenders: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


