name: simple_json_persistence
description: Flutter data storage based on simple json files with support for multiple storage instances, streams, etc.
version: 0.1.1
author: Herbert Poul <herbert@poul.at>
homepage: https://github.com/hpoul/simple_json_persistence

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.0.0 <2.0.0'
  path: '>=1.5.0 <2.0.0'
  logging: '>=0.10.0 <1.0.0'
  rxdart: '>=0.22.0 <1.0.0'
  path_provider: '>=1.1.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

dependency_overrides:
  pedantic: ^1.8.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


