name: simple_json_persistence
description: Flutter data storage based on simple json files with support for multiple
  storage instances, streams, etc.
version: 1.0.2
homepage: https://github.com/hpoul/simple_json_persistence

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: '>=1.1.0 <2.0.0'
  path: '>=1.5.0 <2.0.0'
  logging: '>=0.10.0 <1.0.0'
  rxdart: '>=0.23.0 <1.0.0'
  path_provider: '>=1.4.0 <2.0.0'
  synchronized: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
#  test: ">=1.5.0 <2.0.0"
  pedantic: ^1.8.0+1
  fake_async: ^1.1.0
  logging_appenders: ^0.4.2+2

dependency_overrides:
  pedantic: ^1.8.0+1
#  meta: ^1.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


